riscv/riscv-openocd

src/flash/nor/fespi.c

The target may have already configured its clock to run at a higher frequency and would have set SCKDIV and other dividers at that time. Don't restore the SCKDIV to its default or the flash interface may run too fast and programming will fail.
Otherwise, the default value is fine and there is no need to write SCKDIV.

Don't write SCKDIV when flashing

---

src/flash/nor/fespi.c

This fixes the following warning (turned fatal with `-Werror`) on i686-pc-linux-gnu:
```
fespi.c: In function 'fespi_write':
fespi.c:838:3: error: format '%ld' expects argument of type 'long int', but argument 6 has type 'unsigned int' [-Werror=format=]
LOG_WARNING("Couldn't allocate %ld-byte working area.",
^
cc1: all warnings being treated as errors
```

Use portable format specifier for size_t

---

src/target/riscv/riscv.c

I'd like to perform 'verify' operation after using OpenOCD's 'program' operation for loading into flash. OpenOCD provides for these functions in general looks like it expects them to be implemented as algorithms which run efficiently on the SoC. But, if you at least return an error it OpenOCD will revert to reading memory itself and performing the checks on its own.
As is, I just get a segfault when I try to perform 'verify' operation because the function pointer points to nothing.

riscv: implement skeletons for Memory Blank Check and CRC. 

---

src/flash/nor/fespi.c

I kept getting assertion failures that I was adding more steps than I had allocated for. I wasn't sure where the "/16" came from in your code... "/4" made more sense to me if you're writing one word at a time but not sure.
This fixes my immediate issue but not sure it's the correct fix.

riscv: Increase the number of Algorithm Steps

---

src/flash/nor/fespi.c

which causes this to fail on macOS (and in theory on any platform).
This manifests itself as corrupted data while Flashing

Correct off by 1 in malloc

---

src/target/riscv/riscv.c

This works for flashing the SPI Flash when the running program has interrupts. I don't restore interrupts afterwards, but our SPI flashing code is completely trashing the program space anyway as it is now.
However, not sure this is the most general solution.
Does it make more sense to disable and re-enable interrupts at a higher level? Like, can the fespi SPI Flashing code write the CSR somehow (I couldn't figure out how I can do something like "target_write_csr" from that code). Then it could re-enable interrupts after the code has been fully flashed.

riscv: Globally disable interrupts when running algorithms.

---

src/server/gdb_server.c
src/target/target.c

This is a change in the base OpenOCD code. The RISC-V code returns an error if an exception is encountered when a register is accessed that doesn't exist (which is fairly common possibility in RISC-V). But, that error code is not checked by OpenOCD and is not communicated to GDB.
I'm not sure if this was an intentional omission from OpenOCD.

Use the set/reg register error return code when registers don't exist.

---

src/target/riscv/riscv-013.c

There were a few typos in 0.13 examine() which prevented it from working on a hart which wasn't halted yet.

riscv: Ensure that hart is halted before attempting to examine it.

---

src/target/riscv/riscv-013.c

There is no legitimate reason for DMI failures (as opposed to  DMI BUSY response, which is handled with a retry).
We may need to increase the 'timeout' on the BUSY, but since we aren't handling the case when a dmi_read/write actually fails, we should just abort.

Abort on DMI Failures

---

src/target/riscv/riscv.c

GDB might request registers even if target was not successfully initialized.

 Avoid accessing null target->reg_cache

---

src/target/riscv/riscv-011.c

This is meant to address #51. Only actually set interrupt if 'run' was intended.
I have tested on a HiFive1 and the fix works as expected (I was able to duplicate the double-interrupt behavior before and now it doesn't do it, but I haven't tested that it still works to e.g. program the board).

riscv-v11: Don't perform unexpected operation in cache_write

---

src/target/riscv/riscv-013.c

The first part of this is cosmetic -- I see no reason not to print out the result of the scan (especially the error code), even if we don't care about the actual returned data.
The second part is the actual fix, making sure that 'in' is updated even in dmi_write, because the OP result is needed for dmi_write to properly detect busy.

riscv: v13 -- dmi_write must still check for the OP result

---

src/rtos/riscv_debug.c
src/rtos/riscv_debug.h
src/target/riscv/riscv-013.c
src/target/riscv/riscv.c

Can pass all tests on core 0, all tests on core 1, or when picking a random core for each test. There are no tests that debug both cores at once.
There are 2 fixes:
1. Update the thread list as soon as cores are detected.
2. When setting/clearing triggers, do so on all cores.

Testsuite now passes on multicore target

---

src/target/riscv/riscv-013.c
src/target/riscv/riscv.c
src/target/riscv/riscv.h

I just smoke tested this: I can run and halt both harts on my system, but that's all I tested.  I suspect we need to sprinkle riscv_hart_enabled() all over the place (at least in the hardware breakpoint code), but I think we're pretty close.
I haven't tested this at all in RTOS mode.

Fix the multi-GDB mode bugs

---

src/target/riscv/debug_defines.h

This should also fix bugs on ILP32 systems.  IIRC these are all autogenerated from somewhere, we should fix it there rather than just using sed.

Use LL for 64-bit defines, as Windows is LLP64

---

src/target/riscv/riscv-011.c
src/target/riscv/riscv-013.c
src/target/riscv/riscv.c
src/target/riscv/riscv.h

When first connecting to a target, have the debugger disable any
hardware triggers that are set by a previously connected debugger.
The 0.11 code already did this, but 0.13 did not.
To achieve this I decided to share the code to enumerate triggers
between 0.11 and 0.13, which required me to implement get_register() and
set_register() for 0.11, which made the whole change a lot larger than
you might have guessed.
Hopefully this sets us up to in the future share the code to set/remove
triggers as well.

Disable debugger-set triggers on connect

---

src/target/riscv/riscv-011.c
src/target/riscv/riscv-013.c
src/target/riscv/riscv.c
src/target/riscv/riscv.h

The actual implementation of triggers didn't change between those two
versions, so there's no need to duplicate the code.
In the process, I also fixed a minor multicore bug where tselect didn't
always get written on all harts.

Share trigger code between 0.11 and 0.13 code.

---

src/server/server.c

This is essential when a test environment asks OpenOCD to listen on port
0, so that the environment can easily discover which port is actually
being used.
I added this so the test environment can work even when OpenOCD is run under strace/valgrind.

Print out which port OpenOCD is listening on.

---

src/server/gdb_server.c
src/server/server.c

Usually incrementing to get the next port is a good idea, but when set
to 0 the idea is to find an arbitrary unallocated port. 1 is almost
certainly not helpful.

When gdb_port is 0, don't increment it.

---

src/target/riscv/riscv-013.c

This change fixes bug that caused GDB to produce incorrect back traces.
Problem was with OpenOCD reading one additional word beyond the requested range. In this case GDB was reading program stack located at the very top of the RAM, so the last word was outside of valid memory range. The solution was to disable abstract command autoexec for the last read.

Fix reads beyond requested memory range

---

src/target/riscv/riscv-013.c

My previous version of fix used reads from cached program buffer - this caused tests from riscv-tests/debug to fail. With this fix tests are passing and GDB shows the correct stack trace.

Fe 402 fix

---

src/target/riscv/riscv-013.c

This makes all the MemTest* tests pass.
It looks like, only when run in a series of tests, DebugCompareSections fails on spike64. Still looking at that, but I think this is an improvement nonetheless.

Fix a corner case in block memory read.
